version: "3.4"

volumes:
  mongodb:
  mongodb_backup:
  webroot:
  ssl_certs:
  letsencrypt_logs:
  letsencrypt_var:

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb_backup
        target: /backup
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${MONGO_ROOT_USERNAME} -p ${MONGO_ROOT_PASSWORD} --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  cvtool:
    image: bransom/cvtool
    depends_on:
      - mongodb
    restart: always
    environment:
      - REDIRECT_CONNECTION_STRING=http://${HTTP_HOST}:${HTTP_PORT}/
      - HTTPS_CONNECTION_STRING=https://${HTTP_HOST}:${HTTPS_PORT}/?/ssl_certs/live/${HTTP_HOST}/privkey.pem:/ssl_certs/live/${HTTP_HOST}/fullchain.pem
      - AUTH_CONNECTION_STRING=https://login.microsoftonline.com/${OAUTH_TENANT_ID}/v2.0?${OAUTH_CLIENT_ID}:${OAUTH_CLIENT_SECRET}
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/cvtool?authSource=admin
      - CONTROL_CONNECTION_STRING=http://127.0.0.1:${CONTROL_PORT}/
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
      - type: volume
        source: ssl_certs
        target: /ssl_certs
        read_only: true
      - type: volume
        source: webroot
        target: /webroot
        read_only: true
      - type: volume
        source: cvtool_backup
        target: /backup
    healthcheck:
      test: echo 'wget -qO- https://${HTTP_HOST}:${HTTP_PORT}/health' | grep '"outcome":"UP"'
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  letsencrypt:
    image: certbot/certbot
    depends_on:
      - cvtool
    volumes:
      - type: volume
        source: ssl_certs
        target: /etc/letsencrypt
      - type: volume
        source: webroot
        target: /data/letsencrypt
      - type: volume
        source: letsencrypt_logs
        target: /var/log/letsencrypt
      - type: volume
        source: letsencrypt_var
        target: /var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/data/letsencrypt --register-unsafely-without-email --agree-tos --quiet -d ${HTTP_HOST}
