version: "3.2"

networks:
  cvtool_network:
    driver: bridge

volumes:
  mongodb:
  webroot:
  ssl_certs:
  letsencrypt_logs:
  letsencrypt_var:

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - cvtool_network
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb
        target: /data/db

  cvtool:
    image: bransom/cvtool
    depends_on:
      - mongodb
    restart: always
    environment:
      - HTTPS_CONNECTION_STRING=https://${HOST_NAME}:443/?/ssl_certs/live/${HOST_NAME}/privkey.pem:/ssl_certs/live/${HOST_NAME}/fullchain.pem
      - AUTH_CONNECTION_STRING=https://login.microsoftonline.com/${OAUTH_TENANT_ID}/v2.0?${OAUTH_CLIENT_ID}:${OAUTH_CLIENT_SECRET}
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/cvtool?authSource=admin
    networks:
      - cvtool_network
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: volume
        source: ssl_certs
        target: /ssl_certs
        read_only: true
      - type: volume
        source: webroot
        target: /webroot
        read_only: true

  letsencrypt:
    image: certbot/certbot
    depends_on:
      - cvtool
    networks:
      - cvtool_network
    volumes:
      - type: volume
        source: ssl_certs
        target: /etc/letsencrypt
      - type: volume
        source: webroot
        target: /data/letsencrypt
      - type: volume
        source: letsencrypt_logs
        target: /var/log/letsencrypt
      - type: volume
        source: letsencrypt_var
        target: /var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/data/letsencrypt --register-unsafely-without-email --agree-tos -d ${HOST_NAME}

