version: "3.2"

services:

  cvtool:
    image: bransom/cvtool
    restart: always
    environment:
      - HTTPS_CONNECTION_STRING=https://${HOST_NAME}:443/?${SSL_KEY_PATH}:${SSL_CERT_PATH}
      - AUTH_CONNECTION_STRING=https://login.microsoftonline.com/${OAUTH_TENANT_ID}/v2.0?${OAUTH_CLIENT_ID}:${OAUTH_CLIENT_SECRET}
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/cvtool?authSource=admin
    networks:
      - cvtool-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: ssl_certs
        target: /ssl_certs
        read_only: true
      - type: volume
        source: webroot
        target: /webroot

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - type: volume
#        source: ssl_certs
#        target: /etc/letsencrypt
#      - type: volume
#        source: webroot
#        target: /var/www/certbot

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - cvtool-network
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb
        target: /data/db

networks:
  cvtool-network:
    driver: bridge

volumes:
  ssl_certs:
  webroot:
  mongodb:
