= Valori CVtool

React + Redux + Kotlin + vert.x + MongoDB + Docker application to edit and maintain curriculum vitae, see https://cvtool.valori.nl/[cvtool.valori.nl].

== Development environment

=== _Pre-requisites_

* Windows 10 Home
* Virtualization in BIOS enabled

=== _Download and install the following_

* https://jdk.java.net/[Java OpenJDK]
* https://git-scm.com/[Git (for Windows)]
* https://www.jetbrains.com/idea/download/#section=windows[IntelliJ IDEA Community Edition]
* https://code.visualstudio.com/docs/?dv=win[Visual Studio Code]
* https://www.mongodb.com/try/download/community[MongoDB Community server and client]
* https://www.mongodb.com/try/download/database-tools[MongoDB Database Tools]
* https://hub.docker.com/editions/community/docker-ce-desktop-windows/[Docker Desktop]
* https://www.bitvise.com/ssh-client-download[BitWise SSH client]

=== _Setup Visual Studio Code_

* Install ESlint plugin
* Open project subdirectory `/cvtool-frontend/`
* Add `./node` to the PATH environment variable.
* Add these patterns to the _Search: Exclude_ settings:

    **/dist
    **/node
    **/target

== Configure server

See `scripts/clean_install_BladeVPS.sh`.

Create file `/secret/.env`, make it inaccessible for 'outsiders' and fill-in secrets, see `scripts\.env.example`.

== Configure SSL for local development

1. Get yourself an SSL certificate in pem-format (see `scripts\*.sh`).
2. Make sure the Docker volumes for letsencrypt are present (run `docker\docker-compose.yaml` if needed).
3. Copy directory `docker/letsencrypt certs` to volume _letsencrypt_certs_.
4. Copy the SSL certificate files to the right location in volume _letsencrypt_certs_. See also the nginx configuration in `docker\default.conf.template`.
5. Generate or download Diffie-Hellman parameters and store it in the root of volume _letsencrypt_certs_, see `docker\default.conf.template.
6. Copy directory `docker/letsencrypt_webroot` to volume _letsencrypt_webroot_.
7. Restart the letsencrypt container.

== Backup/restore

See `scripts\cvtool_*.sh`.
Data retention is 120 days.

 #!/usr/bin/env sh
 . /secret/.env
 lftp -e " \
     set ftp:ssl-allow true; \
     set ssl:verify-certificate no; \
     open -u ${LFTP_USERNAME},${LFTP_PASSWORD} ${LFTP_HOST} \
     "

== Helpful commands

=== Initialize server

 # Create MongoDB indexes
 scripts/cvtool_initialize_mongodb.sh
 # Restart CVtool-frontend server to load a new certificate
 docker container restart "$(docker ps -aqf 'ancestor=bransom/cvtool-frontend')"

=== Build and publish docker images

 docker build --no-cache=true -t bransom/cvtool-backend - < Dockerfile-backend
 docker build --no-cache=true -t bransom/cvtool-frontend - < Dockerfile-frontend
 docker push bransom/cvtool-backend
 docker push bransom/cvtool-frontend

=== Deploy

 docker pull bransom/cvtool-backend
 docker pull bransom/cvtool-frontend
 docker-compose -f docker-compose.yaml --env-file=/secret/.env up -d
 docker container prune -f
 docker image prune -f

== Docker commands

 # Logs
 docker logs "$(docker ps -aqf 'ancestor=bransom/cvtool-backend')"
 # Container shell
 docker exec -it "$(docker ps -aqf 'ancestor=bransom/cvtool-backend')" sh
 # System entropy
 cat /proc/sys/kernel/random/entropy_avail

 # Volumes Linux
 /var/lib/docker/volumes/
 # Volumes Windows
 \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes

== MongoDB

=== Import/export collections

 #   businessUnit
 #   account
 #   authorization
 #   cv
 #   education
 #   training
 #   skill
 #   publication
 #   reference
 #   experience
 mongoimport --uri mongodb://localhost:27017/cvtool --jsonArray --stopOnError --mode=upsert --file=skill.json
 mongoexport --uri mongodb://localhost:27017/cvtool --jsonArray --collection=skill --out=skill.json

 # Windows
 FOR /R %i IN (exported\json\*.json) DO ^
 mongoimport --file=%i --jsonArray --stopOnError --mode=upsert ^
   --uri mongodb://localhost:27017/cvtool
 # Linux
 ls -1 exported\json\*.json | while read jsonfile; do \
   --file=$jsonfile --jsonArray --stopOnError --mode=upsert \
   --uri mongodb://localhost:27017/cvtool; \
 done

==== mongo shell

 use cvtool
 db.education.updateMany({}, {"$rename": {"year": "yearTo"}})
 db.account.updateMany({}, {"$unset": {"privileges": ""}})
 db.skill.updateMany({"category": {"$in": ["LANGUAGES", "BRANCHES", "EXPERTISE", "PROGRAMMING", "TOOLS", "METHODS", "DATABASES", "APPLICATIONS", "OS_NETWORKS"]}},
   {"$set": {"category": "EXPERTISE"}})
 db.role.renameCollection("authorization")
 db.skill.updateMany(
   { "includeInCv": { "$exists": false } },
   { "$set": { "includeInCv": true } });
 db.authorization.updateMany(
   { "level": { "$eq": "EE_LEAD" } },
   { "$set": { "level": "UNIT_LEAD" } });

 db.audit_log.updateMany({}, {"$rename": {"accountId": "editorAccountId"}});
 db.audit_log.updateMany({}, {"$rename": {"cvId": "cvAccountId"}});
 db.audit_log.find({
    $and: [
      { cvAccountId: null },
      { entity: { $nin: ["account", "authorization", "businessUnit"] } }
    ]
   })
   .forEach(elem =>
      db.audit_log.updateOne(
        { _id: elem._id },
        { $set: { cvAccountId: elem.editorAccountId } }
      )
   );

Full text search:

 db.experience.find(
   {"$text": {"$search": "c#"}},
   {"score": {$meta: "textScore"}}
 ).sort({"score": {"$meta": "textScore"}})
 db.skill.find({"$text": {"$search": "c#"}})
 db.skill.find(
   {"$text": {"$search": "c#"}},
   {"score": {"$meta": "textScore"}}
 ).sort({"score": {"$meta": "textScore"}})

Find `characteristics` that have no associated `account`:

 db.characteristics.aggregate( [
     {
       $lookup: {
         from: "account",
         localField: "accountId",
         foreignField: "_id",
         as: "tassociated_account"
       }
     },
     {
       $match: { "associated_account.0": { $exists: false } }
     }
   ]
 )