= Valori CVtool

React + Redux + Kotlin + vert.x + MongoDB + Docker application to edit and maintain curriculum vitae, see https://cvtool.valori.nl/[cvtool.valori.nl].

== Development environment

=== _Pre-requisites_

* Windows 10 Home
* Virtualization in BIOS enabled

=== _Download and install the following_

* https://jdk.java.net/[Java OpenJDK]
* https://git-scm.com/[Git (for Windows)]
* https://www.jetbrains.com/idea/download/#section=windows[IntelliJ IDEA Community Edition]
* https://code.visualstudio.com/docs/?dv=win[Visual Studio Code]
* https://www.mongodb.com/try/download/community[MongoDB Community server and client]
* https://www.mongodb.com/try/download/database-tools[MongoDB Database Tools]
* https://hub.docker.com/editions/community/docker-ce-desktop-windows/[Docker Desktop]
* https://www.bitvise.com/ssh-client-download[BitWise SSH client]

=== _Setup Visual Studio Code_

* Install ESlint plugin
* Open project subdirectory `/frontend/`
* Add `./node` to the PATH environment variable.
* Add these patterns to the _Search: Exclude_ settings:

    **/dist
    **/node
    **/target

== Configure server

See `scripts/clean_install_BladeVPS.sh`.

Create file `/secret/.env`, make it inaccessible for 'outsiders' and fill-in secrets, see `scripts\.env.example`.

== Backup/restore

See `scripts\cvtool_*.sh`.
Data retention is 120 days.

 #!/usr/bin/env sh
 . /secret/.env
 lftp -e " \
     set ftp:ssl-allow true; \
     set ssl:verify-certificate no; \
     open -u ${LFTP_USERNAME},${LFTP_PASSWORD} ${LFTP_HOST} \
     "

== Docker commands

=== Build and publish docker image

 docker build --no-cache=true -t bransom/cvtool .
 docker push bransom/cvtool

=== Deploy

 docker pull bransom/cvtool
 docker-compose -f docker-compose.yaml --env-file=/secret/.env up -d
 docker container prune -f
 docker image prune -f

=== Initialize

 # Create MongoDB indexes
 scripts/cvtool_initialize_mongodb.sh
 # Restart CVtool server to load a new certificate
 docker container restart "$(docker ps -aqf 'ancestor=bransom/cvtool')"

=== Logs

 docker logs "$(docker ps -aqf 'ancestor=bransom/cvtool')"

=== Docker volumes

 /var/lib/docker/volumes/
 \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes

== MongoDB commands

=== Import/export collections

 #   businessUnit
 #   account
 #   authorization
 #   cv
 #   education
 #   training
 #   skill
 #   publication
 #   reference
 #   experience
 mongoimport --uri mongodb://localhost:27017/cvtool --jsonArray --stopOnError --mode=upsert --file=skill.json
 mongoexport --uri mongodb://localhost:27017/cvtool --jsonArray --collection=skill --out=skill.json

 # Windows
 FOR /R %i IN (exported\json\*.json) DO ^
 mongoimport --file=%i --jsonArray --stopOnError --mode=upsert ^
   --uri mongodb://localhost:27017/cvtool
 # Linux
 ls -1 exported\json\*.json | while read jsonfile; do \
   --file=$jsonfile --jsonArray --stopOnError --mode=upsert \
   --uri mongodb://localhost:27017/cvtool; \
 done

==== mongo shell

 use cvtool
 db.education.updateMany({}, {"$rename": {"year": "yearTo"}})
 db.account.updateMany({}, {"$unset": {"privileges": ""}})
 db.skill.updateMany({"category": {"$in": ["LANGUAGES", "BRANCHES", "EXPERTISE", "PROGRAMMING", "TOOLS", "METHODS", "DATABASES", "APPLICATIONS", "OS_NETWORKS"]}},
   {"$set": {"category": "EXPERTISE"}})
 db.role.renameCollection("authorization")

 db.experience.find(
   {"$text": {"$search": "c#"}},
   {"score": {$meta: "textScore"}}
 ).sort({"score": {"$meta": "textScore"}})
 db.skill.find({"$text": {"$search": "c#"}})
 db.skill.find(
   {"$text": {"$search": "c#"}},
   {"score": {"$meta": "textScore"}}
 ).sort({"score": {"$meta": "textScore"}})