########################################################################################################################
# Compose a container for building the CVtool-frontend.
########################################################################################################################
FROM eclipse-temurin:17-jre-alpine as builder

# Add git, maven and binutils, needed by nodejs.
RUN apk --update add \
    binutils \
    git \
    maven

RUN mkdir /build
WORKDIR /build

# Copy the source code.
RUN git clone https://github.com/RobBosman/valori.CVtool.git .

# Build the frontend.
RUN mvn --projects cvtool-frontend --also-make clean verify

WORKDIR /


########################################################################################################################
# Compose the final CVtool-frontend container.
########################################################################################################################
FROM nginx:alpine
MAINTAINER RobBosman@valori.nl

# Copy nginx configuration.
COPY --from=builder /build/docker/default.conf.template /etc/nginx/templates/

RUN mkdir -p /www/cvtool-frontend
WORKDIR /www/cvtool-frontend

# Copy and unzip the jar with frontend code.
COPY --from=builder /build/cvtool-frontend/target/*.jar .
RUN unzip *.jar
RUN rm *.jar

WORKDIR /
