########################################################################################################################
# Compose a container for building the CVtool-backend.
########################################################################################################################
FROM eclipse-temurin:23-jdk-alpine AS builder
RUN apt-get -y update --no-cache
RUN apt-get -y upgrade --no-cache

# Add git, maven and binutils, needed by jlink.
RUN apk --update add \
    binutils \
    git \
    maven

RUN mkdir /build
WORKDIR /build

# Copy the source code.
RUN git clone https://github.com/RobBosman/valori.CVtool.git --branch master .

# Build the backend.
RUN mvn clean verify --projects cvtool-backend --also-make

# Move the executable code to a suitable location.
RUN mv cvtool-backend/target/*-fat.jar cvtool-fat.jar

WORKDIR /


########################################################################################################################
# Compose the final CVtool-backend container.
########################################################################################################################
FROM eclipse-temurin:23-jre-alpine
LABEL maintainer=RobBosman@valori.nl
SHELL ["/bin/sh", "-c"]
RUN apt-get -y update --no-cache
RUN apt-get -y upgrade --no-cache

# Copy the executable code.
COPY --from=builder /build/cvtool-fat.jar /cvtool-fat.jar

# Run the CVtool backend app.
CMD java -jar /cvtool-fat.jar
