########################################################################################################################
# Compose a container for building the CVtool-frontend.
########################################################################################################################
FROM eclipse-temurin:23-jdk-alpine AS builder

# Add git, maven and binutils, needed by nodejs.
RUN apk --update add \
    binutils \
    git \
    maven

RUN mkdir /build
WORKDIR /build

# Copy the source code.
RUN git clone https://github.com/RobBosman/valori.CVtool.git --branch master .

# Build the frontend.
RUN mvn clean verify -Dskip-dependency-check=true --projects cvtool-frontend --also-make

WORKDIR /


########################################################################################################################
# Compose the final CVtool-frontend container.
########################################################################################################################
FROM nginx:alpine
LABEL maintainer=RobBosman@valori.nl
SHELL ["/bin/sh", "-c"]

# Copy nginx configuration.
COPY --from=builder /build/docker/default.conf.template /etc/nginx/templates/

RUN mkdir -p /www/cvtool-frontend
WORKDIR /www/cvtool-frontend

# Copy and unzip the jar with frontend code.
COPY --from=builder /build/cvtool-frontend/target/*.jar .
RUN unzip *.jar
RUN rm *.jar

WORKDIR /
