var db = db.getSiblingDB('cvtool');
db.account.dropIndexes();
db.account.createIndex({ email: 1}, { unique: true });
db.authorization.dropIndexes();
db.authorization.createIndex({ accountId: 1});
db.characteristics.dropIndexes();
db.characteristics.createIndex({ accountId: 1});
db.education.dropIndexes();
db.education.createIndex({ accountId: 1});
db.training.dropIndexes();
db.training.createIndex({ accountId: 1});
db.skill.dropIndexes();
db.skill.createIndex({ accountId: 1});
db.skill.createIndex({ 'description.nl_NL': 'text', 'description.uk_UK': 'text', 'explanation.nl_NL': 'text', 'explanation.uk_UK': 'text' });
db.publication.dropIndexes();
db.publication.createIndex({ accountId: 1});
db.reference.dropIndexes();
db.reference.createIndex({ accountId: 1});
db.experience.dropIndexes();
db.experience.createIndex({ accountId: 1});
db.experience.createIndex({ '$**': 'text' });
db.audit_log.dropIndexes();
db.audit_log.createIndex({ cvAccountId: 1});
db.audit_log.createIndex({ editorAccountId: 1});