@ECHO OFF

SET ENV_FILE=\secret\.env

SETLOCAL
FOR /F "TOKENS=*" %%i in ('type %ENV_FILE%') do SET %%i
ECHO.
ECHO CONTROL_CONNECTION_STRING=http://localhost:%CONTROL_PORT%
ECHO REDIRECT_CONNECTION_STRING=http://%HTTP_HOST%:%HTTP_PORT%
ECHO HTTPS_CONNECTION_STRING=https://%HTTP_HOST%:%HTTPS_PORT%/?/ssl_certs/live/%HTTP_HOS%/privkey.pem:/ssl_certs/live/%HTTP_HOST%/fullchain.pem
ECHO AUTH_CONNECTION_STRING=https://login.microsoftonline.com/%OAUTH_TENANT_ID%/v2.0?%OAUTH_CLIENT_ID%:%OAUTH_CLIENT_SECRET%
ECHO MONGO_CONNECTION_STRING=mongodb://%MONGO_ROOT_USERNAME%:%MONGO_ROOT_PASSWORD%@mongodb:27017/cvtool?authSource=admin
ECHO.
ENDLOCAL